// metro.config.js
const { getDefaultConfig } = require('expo/metro-config');  // extend Expo’s defaults :contentReference[oaicite:0]{index=0}

const config = getDefaultConfig(__dirname);                  // template generated by `npx expo customize metro.config.js` :contentReference[oaicite:1]{index=1}

// —— minimal tweaks ——
// 1️⃣ Allow Firebase’s CommonJS modules (*.cjs) to resolve
config.resolver.sourceExts.push('cjs');                      // see “Adding more file extensions” :contentReference[oaicite:2]{index=2}

// 2️⃣ If you hit “package exports” resolution issues, opt-out (SDK 48+)
config.resolver.unstable_enablePackageExports = false;       // roll back to classic lookup 

module.exports = config;                                     // export the merged config :contentReference[oaicite:4]{index=4}
